import type { EngineMetadata } from '@aidex/catalog';
import { MarketingEngineId } from '../identifiers.js';

/**
 * Phase 3: every entry is now `version: '1.0.0'` — all 14 engines are
 * AI-backed (prompt → provider → structured result). Categories are
 * reused from `@aidex/document`/`@aidex/design` wherever the same concept
 * genuinely recurs (`generation`, `transformation`, `analysis`,
 * `planning`, `summarization`, `marketing`) — every category below already
 * exists elsewhere in the catalog, zero new ones invented, so
 * `findByCategory()` demonstrably groups engines *across* Feature Packs.
 * `marketing` in particular is reused from `design.banner`/
 * `design.social-post` — this pack's `social.caption`/`social.hashtags`
 * genuinely belong in the same group as those two design engines.
 */
export const MARKETING_ENGINE_METADATA: readonly EngineMetadata[] = [
  {
    id: MarketingEngineId.CampaignPlan,
    name: 'Campaign Plan',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Plans a marketing campaign — objectives, channels, and summary — from a creative brief.',
    requestType: 'CampaignPlanRequest',
    responseType: 'CampaignPlanResult',
    tags: ['marketing', 'campaign', 'planning'],
    category: 'generation',
  },
  {
    id: MarketingEngineId.CampaignBrief,
    name: 'Campaign Brief',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Generates a formal campaign brief document from a raw creative idea.',
    requestType: 'CampaignBriefRequest',
    responseType: 'CampaignBriefResult',
    tags: ['marketing', 'campaign', 'brief'],
    category: 'generation',
  },
  {
    id: MarketingEngineId.CampaignCalendar,
    name: 'Campaign Calendar',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Plans a day-by-day content and activity calendar for an already-planned campaign.',
    requestType: 'CampaignCalendarRequest',
    responseType: 'CampaignCalendarResult',
    tags: ['marketing', 'campaign', 'calendar'],
    category: 'planning',
  },
  {
    id: MarketingEngineId.SeoKeywords,
    name: 'SEO Keywords',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Generates a keyword list with estimated volume and difficulty from a topic brief.',
    requestType: 'SeoKeywordsRequest',
    responseType: 'SeoKeywordsResult',
    tags: ['marketing', 'seo', 'keywords'],
    category: 'generation',
  },
  {
    id: MarketingEngineId.SeoMeta,
    name: 'SEO Meta',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Generates an SEO title and meta description from existing page content.',
    requestType: 'SeoMetaRequest',
    responseType: 'SeoMetaResult',
    tags: ['marketing', 'seo', 'meta'],
    category: 'transformation',
  },
  {
    id: MarketingEngineId.SeoAudit,
    name: 'SEO Audit',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Audits an existing page or URL for SEO issues and produces a scored report.',
    requestType: 'SeoAuditRequest',
    responseType: 'SeoAuditResult',
    tags: ['marketing', 'seo', 'audit'],
    category: 'analysis',
  },
  {
    id: MarketingEngineId.SocialCaption,
    name: 'Social Caption',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Generates a social media post caption from a creative brief.',
    requestType: 'SocialCaptionRequest',
    responseType: 'SocialCaptionResult',
    tags: ['marketing', 'social', 'caption'],
    category: 'marketing',
  },
  {
    id: MarketingEngineId.SocialHashtags,
    name: 'Social Hashtags',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Generates a relevant hashtag set for a social media post from a creative brief.',
    requestType: 'SocialHashtagsRequest',
    responseType: 'SocialHashtagsResult',
    tags: ['marketing', 'social', 'hashtags'],
    category: 'marketing',
  },
  {
    id: MarketingEngineId.SocialSchedule,
    name: 'Social Schedule',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Plans a publish schedule for a set of already-written social media posts.',
    requestType: 'SocialScheduleRequest',
    responseType: 'SocialScheduleResult',
    tags: ['marketing', 'social', 'schedule'],
    category: 'planning',
  },
  {
    id: MarketingEngineId.EmailSubject,
    name: 'Email Subject',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Generates email subject line variants from a creative brief.',
    requestType: 'EmailSubjectRequest',
    responseType: 'EmailSubjectResult',
    tags: ['marketing', 'email', 'subject'],
    category: 'generation',
  },
  {
    id: MarketingEngineId.EmailCopy,
    name: 'Email Copy',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Generates a subject line and body copy for a marketing email from a creative brief.',
    requestType: 'EmailCopyRequest',
    responseType: 'EmailCopyResult',
    tags: ['marketing', 'email', 'copy'],
    category: 'generation',
  },
  {
    id: MarketingEngineId.EmailSequence,
    name: 'Email Sequence',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Generates a multi-step email drip sequence from a creative brief.',
    requestType: 'EmailSequenceRequest',
    responseType: 'EmailSequenceResult',
    tags: ['marketing', 'email', 'sequence'],
    category: 'generation',
  },
  {
    id: MarketingEngineId.AnalyticsSummary,
    name: 'Analytics Summary',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Summarizes a set of marketing metrics into a short narrative summary with highlights.',
    requestType: 'AnalyticsSummaryRequest',
    responseType: 'AnalyticsSummaryResult',
    tags: ['marketing', 'analytics', 'summary'],
    category: 'summarization',
  },
  {
    id: MarketingEngineId.AnalyticsInsights,
    name: 'Analytics Insights',
    featurePack: '@aidex/marketing',
    version: '1.0.0',
    description: 'Derives actionable insights and recommendations from a set of marketing metrics.',
    requestType: 'AnalyticsInsightsRequest',
    responseType: 'AnalyticsInsightsResult',
    tags: ['marketing', 'analytics', 'insights'],
    category: 'analysis',
  },
];
