import type { EngineMetadata } from '@aidex/catalog';
import { ContentEngineId } from './identifiers.js';

/**
 * Hand-written, not derived from the real Engine classes — see
 * @aidex/document's `metadata.ts` for why. `metadata.test.ts` asserts
 * every entry here against the real engine's own fields.
 */
export const CONTENT_ENGINE_METADATA: readonly EngineMetadata[] = [
  {
    id: ContentEngineId.Generate,
    name: 'Content Generate',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Generates new content from a topic using the configured AI provider.',
    requestType: 'ContentGenerateRequest',
    responseType: 'ContentGenerateResult',
    tags: ['content', 'generation', 'ai'],
    category: 'generation',
  },
  {
    id: ContentEngineId.Rewrite,
    name: 'Content Rewrite',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Rewrites existing content using the configured AI provider.',
    requestType: 'ContentRewriteRequest',
    responseType: 'ContentRewriteResult',
    tags: ['content', 'rewrite', 'ai'],
    category: 'transformation',
  },
  {
    id: ContentEngineId.Expand,
    name: 'Content Expand',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Expands existing content with more detail using the configured AI provider.',
    requestType: 'ContentExpandRequest',
    responseType: 'ContentExpandResult',
    tags: ['content', 'expansion', 'ai'],
    category: 'transformation',
  },
  {
    id: ContentEngineId.Shorten,
    name: 'Content Shorten',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Shortens existing content using the configured AI provider.',
    requestType: 'ContentShortenRequest',
    responseType: 'ContentShortenResult',
    tags: ['content', 'shortening', 'ai'],
    category: 'transformation',
  },
  {
    id: ContentEngineId.Translate,
    name: 'Content Translate',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Translates content into a target language using the configured AI provider.',
    requestType: 'ContentTranslateRequest',
    responseType: 'ContentTranslateResult',
    tags: ['content', 'translation', 'ai'],
    category: 'translation',
  },
  {
    id: ContentEngineId.Summarize,
    name: 'Content Summarize',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Summarizes existing content using the configured AI provider.',
    requestType: 'ContentSummarizeRequest',
    responseType: 'ContentSummarizeResult',
    tags: ['content', 'summarization', 'ai'],
    category: 'summarization',
  },
  {
    id: ContentEngineId.Tone,
    name: 'Content Tone',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Adjusts the tone of existing content using the configured AI provider.',
    requestType: 'ContentToneRequest',
    responseType: 'ContentToneResult',
    tags: ['content', 'tone', 'ai'],
    category: 'transformation',
  },
  {
    id: ContentEngineId.Seo,
    name: 'Content SEO',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'SEO-optimizes existing content using the configured AI provider.',
    requestType: 'ContentSeoRequest',
    responseType: 'ContentSeoResult',
    tags: ['content', 'seo', 'marketing', 'ai'],
    category: 'transformation',
  },
  {
    id: ContentEngineId.Blog,
    name: 'Content Blog',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Generates a blog post from a topic using the configured AI provider.',
    requestType: 'ContentBlogRequest',
    responseType: 'ContentBlogResult',
    tags: ['content', 'blog', 'marketing', 'ai'],
    category: 'generation',
  },
  {
    id: ContentEngineId.Email,
    name: 'Content Email',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Generates an email for a given purpose using the configured AI provider.',
    requestType: 'ContentEmailRequest',
    responseType: 'ContentEmailResult',
    tags: ['content', 'email', 'ai'],
    category: 'generation',
  },
  {
    id: ContentEngineId.Social,
    name: 'Content Social',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Generates a social media post from a topic using the configured AI provider.',
    requestType: 'ContentSocialRequest',
    responseType: 'ContentSocialResult',
    tags: ['content', 'social', 'marketing', 'ai'],
    category: 'generation',
  },
  {
    id: ContentEngineId.ProductDescription,
    name: 'Content Product Description',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Generates a product description using the configured AI provider.',
    requestType: 'ContentProductDescriptionRequest',
    responseType: 'ContentProductDescriptionResult',
    tags: ['content', 'ecommerce', 'marketing', 'ai'],
    category: 'generation',
  },
  {
    id: ContentEngineId.Headline,
    name: 'Content Headline',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Generates headline variants for a topic using the configured AI provider.',
    requestType: 'ContentHeadlineRequest',
    responseType: 'ContentHeadlineResult',
    tags: ['content', 'headline', 'marketing', 'ai'],
    category: 'generation',
  },
  {
    id: ContentEngineId.Tagline,
    name: 'Content Tagline',
    featurePack: '@aidex/content',
    version: '1.0.0',
    description: 'Generates tagline variants for a brand using the configured AI provider.',
    requestType: 'ContentTaglineRequest',
    responseType: 'ContentTaglineResult',
    tags: ['content', 'tagline', 'marketing', 'ai'],
    category: 'generation',
  },
];
