import type { EngineMetadata } from '@aidex/catalog';
import { MediaEngineId } from '../identifiers.js';

/**
 * Phase 3: every entry is now `version: '1.0.0'` — all 13 engines are
 * AI-backed (prompt → provider → structured result), unlike
 * `@aidex/design`'s Phase 3, which only upgraded 7 of 14 and left the rest
 * at `0.1.0`. Categories are reused from `@aidex/document`/`@aidex/content`/
 * `@aidex/design` wherever the same concept genuinely recurs (`generation`,
 * `transformation`, `summarization`) — the whole value of a shared Engine
 * Catalog is that `findByCategory()` groups engines *across* Feature
 * Packs, not just within one.
 */
export const MEDIA_ENGINE_METADATA: readonly EngineMetadata[] = [
  {
    id: MediaEngineId.ImageGenerate,
    name: 'Image Generate',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Generates a new image from a creative brief.',
    requestType: 'ImageGenerateRequest',
    responseType: 'ImageGenerateResult',
    tags: ['media', 'image', 'generation'],
    category: 'generation',
  },
  {
    id: MediaEngineId.ImageEdit,
    name: 'Image Edit',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Edits an existing image according to a creative brief.',
    requestType: 'ImageEditRequest',
    responseType: 'ImageEditResult',
    tags: ['media', 'image', 'editing'],
    category: 'transformation',
  },
  {
    id: MediaEngineId.ImageVariant,
    name: 'Image Variant',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Generates variants of an existing image.',
    requestType: 'ImageVariantRequest',
    responseType: 'ImageVariantResult',
    tags: ['media', 'image', 'variation'],
    category: 'generation',
  },
  {
    id: MediaEngineId.ImageOptimize,
    name: 'Image Optimize',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Optimizes an existing image for file size and/or format.',
    requestType: 'ImageOptimizeRequest',
    responseType: 'ImageOptimizeResult',
    tags: ['media', 'image', 'optimization'],
    category: 'transformation',
  },
  {
    id: MediaEngineId.VideoGenerate,
    name: 'Video Generate',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Generates a new video from a creative brief.',
    requestType: 'VideoGenerateRequest',
    responseType: 'VideoGenerateResult',
    tags: ['media', 'video', 'generation'],
    category: 'generation',
  },
  {
    id: MediaEngineId.VideoEdit,
    name: 'Video Edit',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Edits an existing video according to a creative brief.',
    requestType: 'VideoEditRequest',
    responseType: 'VideoEditResult',
    tags: ['media', 'video', 'editing'],
    category: 'transformation',
  },
  {
    id: MediaEngineId.VideoStoryboard,
    name: 'Video Storyboard',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Plans a video as a sequence of storyboard scenes from a creative brief.',
    requestType: 'VideoStoryboardRequest',
    responseType: 'VideoStoryboardResult',
    tags: ['media', 'video', 'storyboard', 'planning'],
    category: 'planning',
  },
  {
    id: MediaEngineId.VideoThumbnail,
    name: 'Video Thumbnail',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Extracts or generates a thumbnail image from an existing video.',
    requestType: 'VideoThumbnailRequest',
    responseType: 'VideoThumbnailResult',
    tags: ['media', 'video', 'thumbnail'],
    category: 'transformation',
  },
  {
    id: MediaEngineId.AudioGenerate,
    name: 'Audio Generate',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Generates new audio from a creative brief.',
    requestType: 'AudioGenerateRequest',
    responseType: 'AudioGenerateResult',
    tags: ['media', 'audio', 'generation'],
    category: 'generation',
  },
  {
    id: MediaEngineId.AudioTranscribe,
    name: 'Audio Transcribe',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Transcribes speech in an existing audio file to text.',
    requestType: 'AudioTranscribeRequest',
    responseType: 'AudioTranscribeResult',
    tags: ['media', 'audio', 'transcription'],
    category: 'transcription',
  },
  {
    id: MediaEngineId.AudioSummarize,
    name: 'Audio Summarize',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Summarizes the content of an existing audio file.',
    requestType: 'AudioSummarizeRequest',
    responseType: 'AudioSummarizeResult',
    tags: ['media', 'audio', 'summarization'],
    category: 'summarization',
  },
  {
    id: MediaEngineId.AssetConvert,
    name: 'Asset Convert',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Converts an existing media asset to a target format.',
    requestType: 'AssetConvertRequest',
    responseType: 'AssetConvertResult',
    tags: ['media', 'asset', 'conversion'],
    category: 'conversion',
  },
  {
    id: MediaEngineId.AssetTransform,
    name: 'Asset Transform',
    featurePack: '@aidex/media',
    version: '1.0.0',
    description: 'Applies a general transform to an existing media asset.',
    requestType: 'AssetTransformRequest',
    responseType: 'AssetTransformResult',
    tags: ['media', 'asset', 'transformation'],
    category: 'transformation',
  },
];
