export { ConnectionManager } from './manager/ConnectionManager.js';
export type { Connection } from './types/Connection.js';
export type { RegisterConnectionInput } from './types/RegisterConnectionInput.js';
export type { ProviderFactory } from './types/ProviderFactory.js';
export type { UpdateConnectionInput } from './manager/ConnectionManager.js';
export type { ResolveOptions } from './manager/ConnectionManager.js';
export { InvalidConnectionConfigError } from './errors/InvalidConnectionConfigError.js';
export { ConnectionNotFoundError } from './errors/ConnectionNotFoundError.js';
export { DisabledConnectionError } from './errors/DisabledConnectionError.js';
export { ProviderFactoryNotFoundError } from './errors/ProviderFactoryNotFoundError.js';
