import type { EngineMetadata } from '@aidex/catalog';
import { DesignEngineId } from './identifiers.js';

/**
 * `version` tracks each id's real implementation state, matching
 * @aidex/document's/@aidex/content's convention exactly: `'1.0.0'` for
 * every one of the 14 ids now that Expansion Phase 3 gave the remaining 7
 * (`design.generate`, `design.layout`, `design.poster`, `design.flyer`,
 * `design.banner`, `design.social-post`, `design.template`) a real,
 * AI-backed Engine — the same upgrade Phase 3 originally gave `design.brand`,
 * `design.logo`, `design.palette`, `design.typography`,
 * `design.business-card`, `design.mockup`, `design.presentation`.
 * `metadata.test.ts` asserts every entry against its real engine's own
 * id/name/description/version — the same drift guard
 * @aidex/document's/@aidex/content's own metadata.test.ts run.
 */
export const DESIGN_ENGINE_METADATA: readonly EngineMetadata[] = [
  {
    id: DesignEngineId.Generate,
    name: 'Design Generate',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a new design asset from a creative brief.',
    requestType: 'DesignGenerateRequest',
    responseType: 'DesignGenerateResult',
    tags: ['design', 'generation'],
    category: 'generation',
  },
  {
    id: DesignEngineId.Layout,
    name: 'Design Layout',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Arranges content blocks into a designed layout.',
    requestType: 'DesignLayoutRequest',
    responseType: 'DesignLayoutResult',
    tags: ['design', 'layout'],
    category: 'layout',
  },
  {
    id: DesignEngineId.Brand,
    name: 'Design Brand',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a brand identity — logo, palette, and typography — from a creative brief.',
    requestType: 'DesignBrandRequest',
    responseType: 'DesignBrandResult',
    tags: ['design', 'branding', 'identity'],
    category: 'branding',
  },
  {
    id: DesignEngineId.Palette,
    name: 'Design Palette',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a color palette, optionally complementing an existing brand.',
    requestType: 'DesignPaletteRequest',
    responseType: 'DesignPaletteResult',
    tags: ['design', 'color', 'palette'],
    category: 'branding',
  },
  {
    id: DesignEngineId.Typography,
    name: 'Design Typography',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates font pairings, optionally complementing an existing brand.',
    requestType: 'DesignTypographyRequest',
    responseType: 'DesignTypographyResult',
    tags: ['design', 'typography', 'fonts'],
    category: 'branding',
  },
  {
    id: DesignEngineId.Poster,
    name: 'Design Poster',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a poster design from a creative brief.',
    requestType: 'DesignPosterRequest',
    responseType: 'DesignPosterResult',
    tags: ['design', 'poster', 'print'],
    category: 'print',
  },
  {
    id: DesignEngineId.Flyer,
    name: 'Design Flyer',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a flyer design, optionally double-sided, from a creative brief.',
    requestType: 'DesignFlyerRequest',
    responseType: 'DesignFlyerResult',
    tags: ['design', 'flyer', 'print', 'marketing'],
    category: 'print',
  },
  {
    id: DesignEngineId.BusinessCard,
    name: 'Design Business Card',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a business card design, optionally double-sided, from a creative brief.',
    requestType: 'DesignBusinessCardRequest',
    responseType: 'DesignBusinessCardResult',
    tags: ['design', 'business-card', 'print', 'branding'],
    category: 'print',
  },
  {
    id: DesignEngineId.Banner,
    name: 'Design Banner',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a banner design for web or print from a creative brief.',
    requestType: 'DesignBannerRequest',
    responseType: 'DesignBannerResult',
    tags: ['design', 'banner', 'marketing', 'web'],
    category: 'marketing',
  },
  {
    id: DesignEngineId.Logo,
    name: 'Design Logo',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a logo, with optional alternate variants, from a creative brief.',
    requestType: 'DesignLogoRequest',
    responseType: 'DesignLogoResult',
    tags: ['design', 'logo', 'branding', 'identity'],
    category: 'branding',
  },
  {
    id: DesignEngineId.SocialPost,
    name: 'Design Social Post',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a social media graphic sized for a target platform.',
    requestType: 'DesignSocialPostRequest',
    responseType: 'DesignSocialPostResult',
    tags: ['design', 'social', 'marketing'],
    category: 'marketing',
  },
  {
    id: DesignEngineId.Presentation,
    name: 'Design Presentation',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a set of presentation slide designs from a creative brief.',
    requestType: 'DesignPresentationRequest',
    responseType: 'DesignPresentationResult',
    tags: ['design', 'presentation', 'slides'],
    category: 'presentation',
  },
  {
    id: DesignEngineId.Mockup,
    name: 'Design Mockup',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Places a design asset into a realistic mockup scene.',
    requestType: 'DesignMockupRequest',
    responseType: 'DesignMockupResult',
    tags: ['design', 'mockup', 'preview'],
    category: 'presentation',
  },
  {
    id: DesignEngineId.Template,
    name: 'Design Template',
    featurePack: '@aidex/design',
    version: '1.0.0',
    description: 'Generates a reusable design template with marked customizable fields.',
    requestType: 'DesignTemplateRequest',
    responseType: 'DesignTemplateResult',
    tags: ['design', 'template', 'reusable'],
    category: 'template',
  },
];
