/** Shapes of the JSON generated by scripts/generate-content.mjs. Keep in sync with that script. */

export interface PackageDoc {
  slug: string;
  name: string;
  version: string;
  description: string;
  category: string;
  keywords: string[];
  license: string;
  repositoryUrl: string;
  engineRange: { node?: string; pnpm?: string };
  dependsOn: string[];
  usedBy: string[];
  dependencyLayer: number;
  hasEsm: boolean;
  hasCjs: boolean;
  hasTypes: boolean;
  treeShakeable: boolean;
  publishedToNpm: boolean;
  frozen: boolean;
  readmeMarkdown: string;
  relatedExampleSlugs: string[];
  relatedGuideSlugs: string[];
}

export interface ExampleDoc {
  slug: string;
  order: number;
  title: string;
  rawTitle: string;
  levelNumber: number;
  levelName: string;
  difficulty: string;
  estimatedTime: string;
  whatProblem: string;
  whyUse: string;
  whenToUse: string;
  requirements: string;
  install: string;
  runCommand: string;
  expectedOutput: string;
  conceptsLearned: string[];
  relatedPackages: string[];
  fullMarkdown: string;
  sourcePath: string;
  prevSlug: string | null;
  nextSlug: string | null;
}

export interface GuideDoc {
  slug: string;
  title: string;
  description: string;
  markdown: string;
  relatedPackages: string[];
  relatedExamples: string[];
  sourcePath: string;
}

export interface RoadmapDoc {
  title: string;
  markdown: string;
}

export interface FaqEntry {
  question: string;
  answer: string;
}

export interface FaqDoc {
  title: string;
  entries: FaqEntry[];
}

export interface HomeDoc {
  introMarkdown: string;
  statusMarkdown: string;
  roadmapTeaser: string;
}

export interface GettingStartedDoc {
  requirements: { node?: string; pnpm?: string };
  quickStartMarkdown: string;
  firstAppMarkdown: string;
}

export interface ContentMeta {
  contentVersion: string;
  status: 'current' | 'future';
  generatedAt: string;
}
